package com.hjw.webService.client.xintong;

import java.io.UnsupportedEncodingException;

import sun.misc.BASE64Encoder;

public class Test {
	
	public static void main(String[] args) {
		
		StringBuffer buffer = new StringBuffer();
		
		buffer.append("<ClinicalDocument xmlns=\"urn:hl7-org:v3\" xmlns:mif=\"urn:hl7-org:v3/mif\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"urn:hl7-org:v3 ..\\sdschemas\\SDA.xsd\">  ");
		buffer.append("  <realmCode code=\"CN\"/>                                                                                                                         ");
		buffer.append("  <typeId root=\"2.16.840.1.113883.1.3\" extension=\"POCD_MT000040\"/>                                                                               ");
		buffer.append("  <templateId root=\"2.16.156.10011.2.1.1.26\"/>                                                                                                   ");
		buffer.append("  <id root=\"2.16.156.10011.1.1\" extension=\"null\"/>                                                                                               ");
		buffer.append("  <code code=\"C0006\" codeSystem=\"2.16.156.10011.2.4\" codeSystemName=\"卫生信息共享文档规范编码体系\"/>                                             ");
		buffer.append("  <title>检查报告</title>                                                                                                                        ");
		buffer.append("  <effectiveTime value=\"20171213000000\"/>                                                                                                        ");
		buffer.append("  <confidentialityCode code=\"N\" codeSystem=\"2.16.840.1.113883.5.25\" codeSystemName=\"Confidentiality\" displayName=\"正常访问保密级别\"/>            ");
		buffer.append("  <languageCode code=\"zh-CN\"/>                                                                                                                   ");
		buffer.append("  <setId/>                                                                                                                                       ");
		buffer.append("  <versionNumber/>                                                                                                                               ");
		buffer.append("  <recordTarget typeCode=\"RCT\" contextControlCode=\"OP\">                                                                                          ");
		buffer.append("    <patientRole classCode=\"PAT\">                                                                                                                ");
		buffer.append("      <id root=\"2.16.156.10011.1.11\" extension=\"E10000000\"/>                                                                                     ");
		buffer.append("      <id root=\"2.16.156.10011.1.12\" extension=\"HA201102113366666\"/>                                                                             ");
		buffer.append("      <id root=\"2.16.156.10011.1.32\" extension=\"Y00000001079\"/>                                                                                  ");
		buffer.append("      <id root=\"2.16.156.10011.1.24\" extension=\"01904160007\"/>                                                                                   ");
		buffer.append("      <id root=\"2.16.156.10011.1.14\"/>                                                                                                           ");
		buffer.append("      <patientType>                                                                                                                              ");
		buffer.append("        <patienttypeCode codeSystem=\"2.16.156.10011.2.3.1.271\" codeSystemName=\"患者类型代码表\"/>                                                 ");
		buffer.append("      </patientType>                                                                                                                             ");
		buffer.append("      <telecom/>                                                                                                                                 ");
		buffer.append("      <patient classCode=\"PSN\" determinerCode=\"INSTANCE\">                                                                                        ");
		buffer.append("        <id root=\"2.16.156.10011.1.3\" extension=\"623234199608293345\"/>                                                                           ");
		buffer.append("        <name>李冬</name>                                                                                                                        ");
		buffer.append("        <administrativeGenderCode code=\"2\" displayName=\"女性\" codeSystem=\"2.16.156.10011.2.3.3.4\" codeSystemName=\"生理性别代码表(GB/T 2261.1)\"/> ");
		buffer.append("        <age unit=\"岁\" value=\"22\"/>                                                                                                              ");
		buffer.append("      </patient>                                                                                                                                 ");
		buffer.append("    </patientRole>                                                                                                                               ");
		buffer.append("  </recordTarget>                                                                                                                                ");
		buffer.append("  <author typeCode=\"AUT\" contextControlCode=\"OP\">                                                                                                ");
		buffer.append("    <time value=\"20171213\"/>                                                                                                                     ");
		buffer.append("    <assignedAuthor classCode=\"ASSIGNED\">                                                                                                        ");
		buffer.append("      <id root=\"2.16.156.10011.1.7\" extension=\"0006\"/>                                                                                           ");
		buffer.append("      <assignedPerson>                                                                                                                           ");
		buffer.append("        <name>赵长梅</name>                                                                                                                      ");
		buffer.append("      </assignedPerson>                                                                                                                          ");
		buffer.append("    </assignedAuthor>                                                                                                                            ");
		buffer.append("  </author>                                                                                                                                      ");
		buffer.append("  <custodian typeCode=\"CST\">                                                                                                                     ");
		buffer.append("    <assignedCustodian classCode=\"ASSIGNED\">                                                                                                     ");
		buffer.append("      <representedCustodianOrganization classCode=\"ORG\" determinerCode=\"INSTANCE\">                                                               ");
		buffer.append("        <id root=\"2.16.156.10011.1.5\" extension=\"44000115-4\"/>                                                                                   ");
		buffer.append("        <name>青海省人民医院</name>                                                                                                              ");
		buffer.append("      </representedCustodianOrganization>                                                                                                        ");
		buffer.append("    </assignedCustodian>                                                                                                                         ");
		buffer.append("  </custodian>                                                                                                                                   ");
		buffer.append("  <legalAuthenticator>                                                                                                                           ");
		buffer.append("    <time/>                                                                                                                                      ");
		buffer.append("    <signatureCode/>                                                                                                                             ");
		buffer.append("    <assignedEntity>                                                                                                                             ");
		buffer.append("      <id root=\"2.16.156.10011.1.4\" extension=\"0006\"/>                                                                                           ");
		buffer.append("      <code displayName=\"审核医师\"/>                                                                                                             ");
		buffer.append("      <assignedPerson classCode=\"PSN\" determinerCode=\"INSTANCE\">                                                                                 ");
		buffer.append("        <name>赵长梅</name>                                                                                                                      ");
		buffer.append("      </assignedPerson>                                                                                                                          ");
		buffer.append("    </assignedEntity>                                                                                                                            ");
		buffer.append("  </legalAuthenticator>                                                                                                                          ");
		buffer.append("  <authenticator>                                                                                                                                ");
		buffer.append("    <time/>                                                                                                                                      ");
		buffer.append("    <signatureCode/>                                                                                                                             ");
		buffer.append("    <assignedEntity>                                                                                                                             ");
		buffer.append("      <id root=\"2.16.156.10011.1.4\" extension=\"123456\"/>                                                                                         ");
		buffer.append("      <code displayName=\"检查技师\"/>                                                                                                             ");
		buffer.append("      <assignedPerson classCode=\"PSN\" determinerCode=\"INSTANCE\">                                                                                 ");
		buffer.append("        <name>没有检查技师姓名</name>                                                                                                            ");
		buffer.append("      </assignedPerson>                                                                                                                          ");
		buffer.append("    </assignedEntity>                                                                                                                            ");
		buffer.append("  </authenticator>                                                                                                                               ");
		buffer.append("  <authenticator>                                                                                                                                ");
		buffer.append("    <time/>                                                                                                                                      ");
		buffer.append("    <signatureCode/>                                                                                                                             ");
		buffer.append("    <assignedEntity>                                                                                                                             ");
		buffer.append("      <id root=\"2.16.156.10011.1.4\" extension=\"123456\"/>                                                                                         ");
		buffer.append("      <code displayName=\"检查医师\"/>                                                                                                             ");
		buffer.append("      <assignedPerson classCode=\"PSN\" determinerCode=\"INSTANCE\">                                                                                 ");
		buffer.append("        <name>123456</name>                                                                                                                      ");
		buffer.append("      </assignedPerson>                                                                                                                          ");
		buffer.append("    </assignedEntity>                                                                                                                            ");
		buffer.append("  </authenticator>                                                                                                                               ");
		buffer.append("  <participant typeCode=\"PRF\">                                                                                                                   ");
		buffer.append("    <time/>                                                                                                                                      ");
		buffer.append("    <associatedEntity classCode=\"ASSIGNED\">                                                                                                      ");
		buffer.append("      <scopingOrganization>                                                                                                                      ");
		buffer.append("        <id root=\"2.16.156.10011.1.26\" extension=\"27\"/>                                                                                          ");
		buffer.append("        <name>体检中心</name>                                                                                                                    ");
		buffer.append("        <asOrganizationPartOf>                                                                                                                   ");
		buffer.append("          <wholeOrganization>                                                                                                                    ");
		buffer.append("            <id root=\"2.16.156.10011.1.5\" extension=\"44000115-4\"/>                                                                               ");
		buffer.append("            <name>青海省人民医院</name>                                                                                                          ");
		buffer.append("          </wholeOrganization>                                                                                                                   ");
		buffer.append("        </asOrganizationPartOf>                                                                                                                  ");
		buffer.append("      </scopingOrganization>                                                                                                                     ");
		buffer.append("    </associatedEntity>                                                                                                                          ");
		buffer.append("  </participant>                                                                                                                                 ");
		buffer.append("  <relatedDocument typeCode=\"RPLC\">                                                                                                              ");
		buffer.append("    <parentDocument>                                                                                                                             ");
		buffer.append("      <id/>                                                                                                                                      ");
		buffer.append("      <setId/>                                                                                                                                   ");
		buffer.append("      <versionNumber/>                                                                                                                           ");
		buffer.append("    </parentDocument>                                                                                                                            ");
		buffer.append("  </relatedDocument>                                                                                                                             ");
		buffer.append("  <componentOf>                                                                                                                                  ");
		buffer.append("    <encompassingEncounter>                                                                                                                      ");
		buffer.append("      <effectiveTime/>                                                                                                                           ");
		buffer.append("      <location>                                                                                                                                 ");
		buffer.append("        <healthCareFacility>                                                                                                                     ");
		buffer.append("          <serviceProviderOrganization>                                                                                                          ");
		buffer.append("            <asOrganizationPartOf classCode=\"PART\">                                                                                              ");
		buffer.append("              <wholeOrganization classCode=\"ORG\" determinerCode=\"INSTANCE\">                                                                      ");
		buffer.append("                <id root=\"2.16.156.10011.1.22\"/>                                                                                                 ");
		buffer.append("                <asOrganizationPartOf classCode=\"PART\">                                                                                          ");
		buffer.append("                  <wholeOrganization classCode=\"ORG\" determinerCode=\"INSTANCE\">                                                                  ");
		buffer.append("                    <id root=\"2.16.156.10011.1.21\"/>                                                                                             ");
		buffer.append("                    <asOrganizationPartOf classCode=\"PART\">                                                                                      ");
		buffer.append("                      <wholeOrganization classCode=\"ORG\" determinerCode=\"INSTANCE\">                                                              ");
		buffer.append("                        <id root=\"2.16.156.10011.1.26\"/>                                                                                         ");
		buffer.append("                        <name/>                                                                                                                  ");
		buffer.append("                        <asOrganizationPartOf classCode=\"PART\">                                                                                  ");
		buffer.append("                          <wholeOrganization classCode=\"ORG\" determinerCode=\"INSTANCE\">                                                          ");
		buffer.append("                            <id root=\"2.16.156.10011.1.27\"/>                                                                                     ");
		buffer.append("                            <name/>                                                                                                              ");
		buffer.append("                            <asOrganizationPartOf classCode=\"PART\">                                                                              ");
		buffer.append("                              <wholeOrganization classCode=\"ORG\" determinerCode=\"INSTANCE\">                                                      ");
		buffer.append("                                <id root=\"2.16.156.10011.1.5\"/>                                                                                  ");
		buffer.append("                                <name/>                                                                                                          ");
		buffer.append("                              </wholeOrganization>                                                                                               ");
		buffer.append("                            </asOrganizationPartOf>                                                                                              ");
		buffer.append("                          </wholeOrganization>                                                                                                   ");
		buffer.append("                        </asOrganizationPartOf>                                                                                                  ");
		buffer.append("                      </wholeOrganization>                                                                                                       ");
		buffer.append("                    </asOrganizationPartOf>                                                                                                      ");
		buffer.append("                  </wholeOrganization>                                                                                                           ");
		buffer.append("                </asOrganizationPartOf>                                                                                                          ");
		buffer.append("              </wholeOrganization>                                                                                                               ");
		buffer.append("            </asOrganizationPartOf>                                                                                                              ");
		buffer.append("          </serviceProviderOrganization>                                                                                                         ");
		buffer.append("        </healthCareFacility>                                                                                                                    ");
		buffer.append("      </location>                                                                                                                                ");
		buffer.append("    </encompassingEncounter>                                                                                                                     ");
		buffer.append("  </componentOf>                                                                                                                                 ");
		buffer.append("  <component>                                                                                                                                    ");
		buffer.append("    <structuredBody>                                                                                                                             ");
		buffer.append("      <component>                                                                                                                                ");
		buffer.append("        <section>                                                                                                                                ");
		buffer.append("          <code code=\"29548-5\" displayName=\"Diagnosis\" codeSystem=\"2.16.840.1.113883.6.1\" codeSystemName=\"LOINC\"/>                               ");
		buffer.append("          <text/>                                                                                                                                ");
		buffer.append("          <entry>                                                                                                                                ");
		buffer.append("            <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                         ");
		buffer.append("              <code code=\"DE05.01.024.00\" displayName=\"诊断代码\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\"/>         ");
		buffer.append("              <effectiveTime value=\"20190201\"/>                                                                                                  ");
		buffer.append("              <value xsi:type=\"CD\" code=\"Z10.100\" displayName=\"健康体检\" codeSystem=\"2.16.156.10011.2.3.3.11\" codeSystemName=\"ICD-10\"/>          ");
		buffer.append("              <performer>                                                                                                                        ");
		buffer.append("                <assignedEntity>                                                                                                                 ");
		buffer.append("                  <id/>                                                                                                                          ");
		buffer.append("                  <representedOrganization>                                                                                                      ");
		buffer.append("                    <name>青海省人民医院</name>                                                                                                  ");
		buffer.append("                  </representedOrganization>                                                                                                     ");
		buffer.append("                </assignedEntity>                                                                                                                ");
		buffer.append("              </performer>                                                                                                                       ");
		buffer.append("            </observation>                                                                                                                       ");
		buffer.append("          </entry>                                                                                                                               ");
		buffer.append("        </section>                                                                                                                               ");
		buffer.append("      </component>                                                                                                                               ");
		buffer.append("      <component>                                                                                                                                ");
		buffer.append("        <section>                                                                                                                                ");
		buffer.append("          <code code=\"10154-3\" displayName=\"CHIEF COMPLAINT\" codeSystem=\"2.16.840.1.113883.6.1\" codeSystemName=\"LOINC\"/>                         ");
		buffer.append("          <text/>                                                                                                                                ");
		buffer.append("          <entry>                                                                                                                                ");
		buffer.append("            <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                         ");
		buffer.append("              <code code=\"DE04.01.119.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"主诉\"/>             ");
		buffer.append("              <value xsi:type=\"ST\">公共机构居民的常规一般性健康查体</value>                                                                      ");
		buffer.append("            </observation>                                                                                                                       ");
		buffer.append("          </entry>                                                                                                                               ");
		buffer.append("        </section>                                                                                                                               ");
		buffer.append("      </component>                                                                                                                               ");
		buffer.append("      <component>                                                                                                                                ");
		buffer.append("        <section>                                                                                                                                ");
		buffer.append("          <code code=\"11450-4\" codeSystem=\"2.16.840.1.113883.6.1\" codeSystemName=\"LOINC\" displayName=\"PROBLEM LIST\"/>                            ");
		buffer.append("          <text/>                                                                                                                                ");
		buffer.append("          <entry>                                                                                                                                ");
		buffer.append("            <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                         ");
		buffer.append("              <code code=\"DE04.01.117.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"症状描述\"/>         ");
		buffer.append("              <effectiveTime>                                                                                                                    ");
		buffer.append("                <low value=\"20190202\"/>                                                                                                          ");
		buffer.append("                <high value=\"20190208\"/>                                                                                                         ");
		buffer.append("              </effectiveTime>                                                                                                                   ");
		buffer.append("              <value xsi:type=\"ST\">公共机构居民的常规一般性健康查体</value>                                                                      ");
		buffer.append("            </observation>                                                                                                                       ");
		buffer.append("          </entry>                                                                                                                               ");
		buffer.append("        </section>                                                                                                                               ");
		buffer.append("      </component>                                                                                                                               ");
		buffer.append("      <component>                                                                                                                                ");
		buffer.append("        <section>                                                                                                                                ");
		buffer.append("          <code code=\"47519-4\" displayName=\"HISTORY OF PROCEDURES\" codeSystem=\"2.16.840.1.113883.6.1\" codeSystemName=\"LOINC\"/>                   ");
		buffer.append("          <text/>                                                                                                                                ");
		buffer.append("          <entry>                                                                                                                                ");
		buffer.append("            <procedure classCode=\"PROC\" moodCode=\"EVN\">                                                                                          ");
		buffer.append("              <code codeSystem=\"2.16.156.10011.2.3.3.12\" codeSystemName=\"ICD-9-CM-3\"/>                                                           ");
		buffer.append("              <statusCode/>                                                                                                                      ");
		buffer.append("              <effectiveTime/>                                                                                                                   ");
		buffer.append("              <targetSiteCode codeSystem=\"2.16.156.10011.2.3.1.266\" codeSystemName=\"操作部位代码表\"/>                                            ");
		buffer.append("              <entryRelationship typeCode=\"COMP\">                                                                                                ");
		buffer.append("                <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                     ");
		buffer.append("                  <code code=\"DE06.00.094.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"手术（操作）名 ");
		buffer.append("                  <value xsi:type=\"ST\"/>                                                                                                         ");
		buffer.append("                </observation>                                                                                                                   ");
		buffer.append("              </entryRelationship>                                                                                                               ");
		buffer.append("              <entryRelationship typeCode=\"COMP\">                                                                                                ");
		buffer.append("                <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                     ");
		buffer.append("                  <code code=\"DE08.50.037.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"介入物名称\"/>   ");
		buffer.append("                  <value xsi:type=\"ST\"/>                                                                                                         ");
		buffer.append("                </observation>                                                                                                                   ");
		buffer.append("              </entryRelationship>                                                                                                               ");
		buffer.append("              <entryRelationship typeCode=\"COMP\">                                                                                                ");
		buffer.append("                <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                     ");
		buffer.append("                  <code code=\"DE06.00.251.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"操作方法描述\"/> ");
		buffer.append("                  <value xsi:type=\"ST\"/>                                                                                                         ");
		buffer.append("                </observation>                                                                                                                   ");
		buffer.append("              </entryRelationship>                                                                                                               ");
		buffer.append("              <entryRelationship typeCode=\"COMP\">                                                                                                ");
		buffer.append("                <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                     ");
		buffer.append("                  <code code=\"DE06.00.250.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"操作次数\"/>     ");
		buffer.append("                  <value xsi:type=\"ST\">12</value>                                                                                                ");
		buffer.append("                </observation>                                                                                                                   ");
		buffer.append("              </entryRelationship>                                                                                                               ");
		buffer.append("              <entryRelationship typeCode=\"COMP\">                                                                                                ");
		buffer.append("                <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                     ");
		buffer.append("                  <code code=\"DE06.00.073.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"麻醉方式代码\"/> ");
		buffer.append("                  <value codeSystem=\"2.16.156.10011.2.3.1.159\" codeSystemName=\"麻醉方法代码表\" xsi:type=\"CD\"/>                                   ");
		buffer.append("                  <performer>                                                                                                                    ");
		buffer.append("                    <assignedEntity>                                                                                                             ");
		buffer.append("                      <id/>                                                                                                                      ");
		buffer.append("                      <assignedPerson>                                                                                                           ");
		buffer.append("                        <name/>                                                                                                                  ");
		buffer.append("                      </assignedPerson>                                                                                                          ");
		buffer.append("                    </assignedEntity>                                                                                                            ");
		buffer.append("                  </performer>                                                                                                                   ");
		buffer.append("                </observation>                                                                                                                   ");
		buffer.append("              </entryRelationship>                                                                                                               ");
		buffer.append("              <entryRelationship typeCode=\"COMP\">                                                                                                ");
		buffer.append("                <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                     ");
		buffer.append("                  <code code=\"DE02.10.028.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"麻醉观察结果\"/> ");
		buffer.append("                  <value xsi:type=\"ST\"/>                                                                                                         ");
		buffer.append("                </observation>                                                                                                                   ");
		buffer.append("              </entryRelationship>                                                                                                               ");
		buffer.append("              <entryRelationship typeCode=\"COMP\">                                                                                                ");
		buffer.append("                <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                     ");
		buffer.append("                  <code code=\"DE06.00.307.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"麻醉中西医标识 ");
		buffer.append("                  <value codeSystem=\"2.16.156.10011.2.3.2.41\" codeSystemName=\"麻醉中西医标识代码表\" xsi:type=\"CD\"/>                              ");
		buffer.append("                </observation>                                                                                                                   ");
		buffer.append("              </entryRelationship>                                                                                                               ");
		buffer.append("            </procedure>                                                                                                                         ");
		buffer.append("          </entry>                                                                                                                               ");
		buffer.append("        </section>                                                                                                                               ");
		buffer.append("      </component>                                                                                                                               ");
		buffer.append("      <component>                                                                                                                                ");
		buffer.append("        <section>                                                                                                                                ");
		buffer.append("          <code code=\"29545-1\" displayName=\"PHYSICAL EXAMINATION\" codeSystem=\"2.16.840.1.113883.6.1\" codeSystemName=\"LOINC\"/>                    ");
		buffer.append("          <text/>                                                                                                                                ");
		buffer.append("          <entry>                                                                                                                                ");
		buffer.append("            <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                         ");
		buffer.append("              <code code=\"DE02.01.079.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"特殊检查标志\"/>     ");
		buffer.append("              <value xsi:type=\"ST\">F</value>                                                                                                     ");
		buffer.append("            </observation>                                                                                                                       ");
		buffer.append("          </entry>                                                                                                                               ");
		buffer.append("          <entry>                                                                                                                                ");
		buffer.append("            <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                         ");
		buffer.append("              <code code=\"DE02.10.027.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"检查方法名称\"/>     ");
		buffer.append("              <value xsi:type=\"ST\">患者接受医学检查项目所采用的检查方法名称</value>                                                              ");
		buffer.append("            </observation>                                                                                                                       ");
		buffer.append("          </entry>                                                                                                                               ");
		buffer.append("          <entry>                                                                                                                                ");
		buffer.append("            <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                         ");
		buffer.append("              <code code=\"DE04.30.018.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"检查类别\"/>         ");
		buffer.append("              <value xsi:type=\"ST\">患者检查项目所属的类别详细描述</value>                                                                        ");
		buffer.append("            </observation>                                                                                                                                  ");
		buffer.append("          </entry>                                                                                                                                          ");
		buffer.append("          <entry>                                                                                                                                           ");
		buffer.append("            <organizer classCode=\"CLUSTER\" moodCode=\"EVN\">                                                                                                  ");
		buffer.append("              <statusCode/>                                                                                                                                 ");
		buffer.append("              <component>                                                                                                                                   ");
		buffer.append("                <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                                ");
		buffer.append("                  <code code=\"DE04.30.019.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"检查项目代码\"/>            ");
		buffer.append("                  <effectiveTime value=\"20120405\"/>                                                                                                         ");
		buffer.append("                  <value xsi:type=\"ST\">患者检查项目在特定编码体系中的代码</value>                                                                           ");
		buffer.append("                  <entryRelationship typeCode=\"COMP\">                                                                                                       ");
		buffer.append("                    <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                            ");
		buffer.append("                      <code code=\"DE04.50.134.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"标本类别\"/>            ");
		buffer.append("                      <effectiveTime>                                                                                                                       ");
		buffer.append("                        <low value=\"20130101110103\"/>                                                                                                       ");
		buffer.append("                        <high value=\"20130102110212\"/>                                                                                                      ");
		buffer.append("                      </effectiveTime>                                                                                                                      ");
		buffer.append("                      <value xsi:type=\"ST\">标本类别</value>                                                                                                 ");
		buffer.append("                    </observation>                                                                                                                          ");
		buffer.append("                  </entryRelationship>                                                                                                                      ");
		buffer.append("                  <entryRelationship typeCode=\"COMP\">                                                                                                       ");
		buffer.append("                    <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                            ");
		buffer.append("                      <code code=\"DE04.50.135.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"标本状态\"/>            ");
		buffer.append("                      <value xsi:type=\"ST\">标本状态</value>                                                                                                 ");
		buffer.append("                    </observation>                                                                                                                          ");
		buffer.append("                  </entryRelationship>                                                                                                                      ");
		buffer.append("                  <entryRelationship typeCode=\"COMP\">                                                                                                       ");
		buffer.append("                    <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                            ");
		buffer.append("                      <code code=\"DE08.50.027.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"标本固定液名称\"/>      ");
		buffer.append("                      <value xsi:type=\"ST\">标本固定液名称</value>                                                                                           ");
		buffer.append("                    </observation>                                                                                                                          ");
		buffer.append("                  </entryRelationship>                                                                                                                      ");
		buffer.append("                </observation>                                                                                                                              ");
		buffer.append("              </component>                                                                                                                                  ");
		buffer.append("              <component>                                                                                                                                   ");
		buffer.append("                <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                                ");
		buffer.append("                  <code code=\"DE04.30.017.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"检查结果代码\"/>            ");
		buffer.append("                  <value xsi:type=\"CD\" code=\"1\" displayName=\"异常\" codeSystem=\"2.16.156.10011.2.3.2.38\" codeSystemName=\"检查/检验结果代码表\"/>              ");
		buffer.append("                </observation>                                                                                                                              ");
		buffer.append("              </component>                                                                                                                                  ");
		buffer.append("              <component>                                                                                                                                   ");
		buffer.append("                <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                                ");
		buffer.append("                  <code code=\"DE04.30.015.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"检查定量结果\"/>            ");
		buffer.append("                  <value xsi:type=\"REAL\" value=\"1.7777\"/>                                                                                                   ");
		buffer.append("                  <entryRelationship typeCode=\"COMP\">                                                                                                       ");
		buffer.append("                    <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                            ");
		buffer.append("                      <code code=\"DE04.30.016.00\" displayName=\"检查定量结果计量单位\" codeSystemName=\"卫生信息数据元目录\" codeSystem=\"2.16.156.10011.2.2.1\"/ ");
		buffer.append("                      <value xsi:type=\"ST\">ml</value>                                                                                                       ");
		buffer.append("                    </observation>                                                                                                                          ");
		buffer.append("                  </entryRelationship>                                                                                                                      ");
		buffer.append("                </observation>                                                                                                                              ");
		buffer.append("              </component>                                                                                                                                  ");
		buffer.append("            </organizer>                                                                                                                                    ");
		buffer.append("          </entry>                                                                                                                                          ");
		buffer.append("        </section>                                                                                                                                          ");
		buffer.append("      </component>                                                                                                                                          ");
		buffer.append("      <component>                                                                                                                                           ");
		buffer.append("        <section>                                                                                                                                           ");
		buffer.append("          <code displayName=\"其他处置章节\"/>                                                                                                                ");
		buffer.append("          <text/>                                                                                                                                           ");
		buffer.append("          <entry typeCode=\"COMP\">                                                                                                                           ");
		buffer.append("            <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                                    ");
		buffer.append("              <code code=\"DE06.00.296.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"诊疗过程描述\"/>                ");
		buffer.append("              <value xsi:type=\"ST\"/>                                                                                                                        ");
		buffer.append("            </observation>                                                                                                                                  ");
		buffer.append("          </entry>                                                                                                                                          ");
		buffer.append("        </section>                                                                                                                                          ");
		buffer.append("      </component>                                                                                                                                          ");
		buffer.append("      <component>                                                                                                                                           ");
		buffer.append("        <section>                                                                                                                                           ");
		buffer.append("          <code displayName=\"检查报告\"/>                                                                                                                    ");
		buffer.append("          <text/>                                                                                                                                           ");
		buffer.append("          <entry>                                                                                                                                           ");
		buffer.append("            <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                                    ");
		buffer.append("              <code code=\"DE04.50.131.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"检查报告结果-客观所见\"/>       ");
		buffer.append("              <value xsi:type=\"ST\">胸廓对称，左下肺纹理增多，且见少许斑片状密度增高影，边缘不清，双肺门结构清楚，双肋膈角锐利，心影未见确切异常。</value>   ");
		buffer.append("            </observation>                                                                                                                                  ");
		buffer.append("          </entry>                                                                                                                                          ");
		buffer.append("          <entry>                                                                                                                                           ");
		buffer.append("            <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                                    ");
		buffer.append("              <code code=\"DE04.50.132.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"检查报告结果-主观提示\"/>       ");
		buffer.append("              <value xsi:type=\"ST\">左下肺纹理增多，左下肺少许炎变可能。 建议结合临床，必要时复查。</value>                                                  ");
		buffer.append("            </observation>                                                                                                                                  ");
		buffer.append("          </entry>                                                                                                                                          ");
		buffer.append("          <entry>                                                                                                                                           ");
		buffer.append("            <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                                    ");
		buffer.append("              <code code=\"DE08.10.026.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"检查报告科室\"/>                ");
		buffer.append("              <value xsi:type=\"ST\">null</value>                                                                                                             ");
		buffer.append("            </observation>                                                                                                                                  ");
		buffer.append("          </entry>                                                                                                                                          ");
		buffer.append("          <entry>                                                                                                                                           ");
		buffer.append("            <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                                    ");
		buffer.append("              <code code=\"DE08.10.013.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"检查报告机构名称\"/>            ");
		buffer.append("              <value xsi:type=\"ST\">青海省人民医院</value>                                                                                                   ");
		buffer.append("            </observation>                                                                                                                                  ");
		buffer.append("          </entry>                                                                                                                                          ");
		buffer.append("          <entry>                                                                                                                                           ");
		buffer.append("            <observation classCode=\"OBS\" moodCode=\"EVN\">                                                                                                    ");
		buffer.append("              <code code=\"DE06.00.179.00\" codeSystem=\"2.16.156.10011.2.2.1\" codeSystemName=\"卫生信息数据元目录\" displayName=\"检查报告备注\"/>                ");
		buffer.append("              <value xsi:type=\"ST\">检查报告备注信息</value>                                                                                                 ");
		buffer.append("            </observation>                                                                                                                                  ");
		buffer.append("          </entry>                                                                                                                                          ");
		buffer.append("        </section>                                                                                                                                          ");
		buffer.append("      </component>                                                                                                                                          ");
		buffer.append("    </structuredBody>                                                                                                                                       ");
		buffer.append("  </component>                                                                                                                                              ");
		buffer.append("</ClinicalDocument>                                                                                                                                         ");

		System.out.println(getBase64(buffer.toString().trim())); 
		
	}
	
	public static String getBase64(String str) {
		byte[] b = null;
		String s = null;
		try {
			b = str.getBytes("utf-8");
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
		if (b != null) {
			s = new BASE64Encoder().encode(b);
		}
		return s;
	}

}
